
# By specifying the type as a 'LoadBalancer', Kubernetes Engine will create an external HTTP load balancer.

apiVersion: v1
kind: Service
metadata:
  name: helloworld-gke
spec:
  type: LoadBalancer
  selector:
    app: helloworld-gke
  ports:
  - port: 80
    targetPort: 8080
---
